In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import cv2

In [20]:
image_path = rf'C:\Users\barki\Downloads\test_image.jpg'

In [21]:
image = cv2.imread(image_path)

In [32]:
# Display given image
def show_image(input_image, image_name = "image"):
    cv2.imshow(image_name, input_image)
    cv2.waitKey(0)
    cv2.destroyWindow(image_name)
    print(f"{image_name}: \n{input_image}\nimage shape: {input_image.shape}")

In [33]:
show_image(image)

image: 
[[[116  91  75]
  [194 174 134]
  [194 174 134]
  ...
  [248 238 215]
  [248 238 215]
  [248 238 215]]

 [[157 133 106]
  [194 174 134]
  [194 174 134]
  ...
  [247 238 215]
  [247 238 215]
  [247 238 215]]

 [[185 163 127]
  [194 174 134]
  [194 174 134]
  ...
  [247 238 215]
  [247 238 215]
  [247 238 215]]

 ...

 [[ 74  80  85]
  [ 74  80  85]
  [ 74  80  85]
  ...
  [ 73  74  82]
  [ 73  74  82]
  [ 73  74  82]]

 [[ 74  80  85]
  [ 74  80  85]
  [ 74  80  85]
  ...
  [ 72  73  81]
  [ 72  73  81]
  [ 72  73  81]]

 [[ 74  80  85]
  [ 74  80  85]
  [ 74  80  85]
  ...
  [ 72  73  81]
  [ 72  73  81]
  [ 72  73  81]]]
image shape: (704, 1279, 3)


In [34]:
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
show_image(gray_image, "gray_image")


gray_image: 
[[ 89 164 164 ... 232 232 232]
 [128 164 164 ... 232 232 232]
 [155 164 164 ... 232 232 232]
 ...
 [ 81  81  81 ...  76  76  76]
 [ 81  81  81 ...  75  75  75]
 [ 81  81  81 ...  75  75  75]]
image shape: (704, 1279)


In [35]:
# Apply gaussian filter on given image, display and return the output image
def apply_gaussian_fitler(input_image, kernel_size = 5, deviation = 0):
    blurred_image = cv2.GaussianBlur(input_image, (kernel_size, kernel_size), deviation)
    show_image(blurred_image, "blurred_image")
    return blurred_image


In [36]:
blurred_image = apply_gaussian_fitler(gray_image)

blurred_image: 
[[146 152 161 ... 232 232 232]
 [150 155 162 ... 232 232 232]
 [158 160 163 ... 232 232 232]
 ...
 [ 81  81  81 ...  76  77  77]
 [ 81  81  81 ...  75  75  76]
 [ 81  81  81 ...  75  75  75]]
image shape: (704, 1279)
